### ISSUE TITLE
Пропозиція для посіву команд

### ISSUE THREAD

**Issue by Peter-Zagriychuk** [table-tennis-it/TableTennisITCup#11]
Пропозиція сіяти команди виключно по командному рейтингу, або як альтернативу до командного додавати частку особистого(наприклад 20-30%,  але не як є зараз) оскільки у нас турнір все ж **командний**, тому не зрозуміле співвідношення особистого до командного як 2 : 1. Ми таким чином нехтуємо командними заслугами. (якшо є аргументована відповідь що до такої формули - пишіть)
Якщо ж команда-новачок то брати за початковий командний рейтинг як сумарний особистий перших 3-х гравців.

**Comment by Igor-Palaguta** [comment]
Перешли на новый рейтинг/симуляцию
http://www.tabletennisit.com/tournaments/kiev-open-2019/simulation
