### ISSUE TITLE
Сеять новые команды учитывая ФНТУ, TTW рейтинги

### ISSUE THREAD

**Issue by Igor-Palaguta** [table-tennis-it/TableTennisITCup#8]

**Comment by BogdanSkochynskyi** [comment]
При чем тут личный рейтинг на других турнирах к командному турниру между айти компаниями? Ладно личный рейтинг в айтишных турнирах...

**Comment by Igor-Palaguta** [comment]
https://github.com/table-tennis-it/TableTennisITCup#6-посев
